### ISSUE TITLE
[gazebo-2] process has died

### ISSUE THREAD

**Issue by logindiamant** [szebedy/autonomous-drone#2] opened 2018-11-14 14:00 UTC
When I'am try to run the simulation, Gazebo is crashed...
Please, tel how to solve this problem?

GAZEBO_PLUGIN_PATH /home/gleb/catkin_ws/px4/build/posix_sitl_default/build_gazebo:
GAZEBO_MODEL_PATH :/home/gleb/catkin_ws/px4/Tools/sitl_gazebo/models
LD_LIBRARY_PATH /home/gleb/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/gleb/catkin_ws/px4/Tools/sitl_gazebo/Build/msgs/:/home/gleb/catkin_ws/px4/build/posix_sitl_default/build_gazebo
... logging to /home/gleb/.ros/log/61f06c14-e814-11e8-8ede-080027bc695c/roslaunch-gleb-VirtualBox-11350.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gleb-VirtualBox:46511/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True
 * /whycon/inner_diameter: 0.08
 * /whycon/outer_diameter: 0.1952
 * /whycon/targets: 1

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    image_view (image_view/image_view)
    mavros (mavros/mavros_node)
    offboard_control (offboard_control/offboard_control)
    rviz (rviz/rviz)
    sitl (px4/px4)
    trajectory_planner (trajectory_planner/trajectory_planner)
    vehicle_spawn_gleb_VirtualBox_11350_5973867746794150957 (gazebo_ros/spawn_model)
    whycon (whycon/whycon)

ROS_MASTER_URI=http://localhost:11311

process[sitl-1]: started with pid [11368]
node name: sitl
data path: /home/gleb/catkin_ws/px4
commands file: /home/gleb/catkin_ws/px4/posix-configs/SITL/init/ekf2/iris
138 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

process[gazebo-2]: started with pid [11376]
process[gazebo_gui-3]: started with pid [11381]
INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
process[vehicle_spawn_gleb_VirtualBox_11350_5973867746794150957-4]: started with pid [11390]
process[mavros-5]: started with pid [11391]
process[image_view-6]: started with pid [11392]
process[whycon-7]: started with pid [11393]
process[trajectory_planner-8]: started with pid [11399]
process[offboard_control-9]: started with pid [11406]
process[rviz-10]: started with pid [11463]
[ INFO] [1542203505.188823035]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1542203505.194197685]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1542203505.194317657]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1542203505.194424784]: GCS bridge disabled
[ INFO] [1542203505.259229984]: Loading file whycon_transforms.yml
[ WARN] [1542203505.259442494]: Could not load "whycon_transforms.yml"
[ INFO] [1542203505.266102412]: Plugin 3dr_radio loaded
[ INFO] [1542203505.270846652]: Plugin 3dr_radio initialized
[ INFO] [1542203505.270989124]: Plugin actuator_control loaded
[ INFO] [1542203505.284609493]: Plugin actuator_control initialized
[ INFO] [1542203505.290883473]: Plugin adsb loaded
[ INFO] [1542203505.303820221]: Plugin adsb initialized
[ INFO] [1542203505.304078769]: Plugin altitude loaded
[ INFO] [1542203505.306792440]: Plugin altitude initialized
[ INFO] [1542203505.306996869]: Plugin cam_imu_sync loaded
[ INFO] [1542203505.308453868]: Plugin cam_imu_sync initialized
[ INFO] [1542203505.308670784]: Plugin command loaded
[ INFO] [1542203505.349226044]: Plugin command initialized
[ INFO] [1542203505.349623746]: Plugin debug_value loaded
[ INFO] [1542203505.375452064]: Plugin debug_value initialized
[ INFO] [1542203505.375504741]: Plugin distance_sensor blacklisted
[ INFO] [1542203505.375702024]: Plugin fake_gps loaded
[ INFO] [1542203505.455923403]: Plugin fake_gps initialized
[ INFO] [1542203505.456173764]: Plugin ftp loaded
[ INFO] [1542203505.485806562]: Plugin ftp initialized
[ INFO] [1542203505.486059645]: Plugin global_position loaded
[ INFO] [1542203505.663500394]: Plugin global_position initialized
[ INFO] [1542203505.663723036]: Plugin gps_rtk loaded
[ INFO] [1542203505.702213763]: Plugin gps_rtk initialized
[ INFO] [1542203505.702516714]: Plugin hil loaded
[ INFO] [1542203505.782027038]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1542203505.784181484]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1542203505.859054162]: Plugin hil initialized
[ INFO] [1542203505.859305781]: Plugin home_position loaded
[ INFO] [1542203505.868240168]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1542203505.869345971]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1542203505.876925366]: Plugin home_position initialized
[ INFO] [1542203505.877182850]: Plugin imu loaded
[ INFO] [1542203505.965255745]: Plugin imu initialized
[ INFO] [1542203505.965497302]: Plugin local_position loaded
[ INFO] [1542203505.982747899]: Plugin local_position initialized
[ INFO] [1542203505.982960132]: Plugin log_transfer loaded
[ INFO] [1542203506.034194753]: Plugin log_transfer initialized
[ INFO] [1542203506.034523213]: Plugin manual_control loaded
[ INFO] [1542203506.064776477]: Plugin manual_control initialized
[ INFO] [1542203506.064975883]: Plugin mocap_pose_estimate loaded
[ INFO] [1542203506.081266985]: Plugin mocap_pose_estimate initialized
[ INFO] [1542203506.081530874]: Plugin obstacle_distance loaded
[ INFO] [1542203506.087675265]: Plugin obstacle_distance initialized
[ INFO] [1542203506.087998036]: Plugin odom loaded
[ INFO] [1542203506.096738932]: Plugin odom initialized
[ INFO] [1542203506.097045612]: Plugin param loaded
[ INFO] [1542203506.116808843]: Plugin param initialized
[ INFO] [1542203506.117069188]: Plugin px4flow loaded
[ INFO] [1542203506.145486656]: Using transport "raw"
[ INFO] [1542203506.170946140]: Plugin px4flow initialized
[ INFO] [1542203506.171006461]: Plugin rangefinder blacklisted
[ INFO] [1542203506.171277278]: Plugin rc_io loaded
[ INFO] [1542203506.185396347]: Plugin rc_io initialized
[ INFO] [1542203506.185459061]: Plugin safety_area blacklisted
[ INFO] [1542203506.185772152]: Plugin setpoint_accel loaded
[ INFO] [1542203506.199605285]: Plugin setpoint_accel initialized
[ INFO] [1542203506.199848090]: Plugin setpoint_attitude loaded
[ INFO] [1542203506.290251820]: Plugin setpoint_attitude initialized
[ INFO] [1542203506.290543699]: Plugin setpoint_position loaded
[ INFO] [1542203506.405884669]: Plugin setpoint_position initialized
[ INFO] [1542203506.406145806]: Plugin setpoint_raw loaded
[ INFO] [1542203506.485738259]: Plugin setpoint_raw initialized
[ INFO] [1542203506.486043694]: Plugin setpoint_velocity loaded
[ INFO] [1542203506.497144625]: Plugin setpoint_velocity initialized
[ INFO] [1542203506.497425035]: Plugin sys_status loaded
[ INFO] [1542203506.521983054]: Plugin sys_status initialized
[ INFO] [1542203506.522239563]: Plugin sys_time loaded
[ INFO] [1542203506.600423179]: TM: Timesync mode: MAVLINK
[ INFO] [1542203506.604360497]: Plugin sys_time initialized
[ INFO] [1542203506.604589543]: Plugin trajectory loaded
[ INFO] [1542203506.696409022]: Plugin trajectory initialized
[ INFO] [1542203506.696658229]: Plugin vfr_hud loaded
[ INFO] [1542203506.697615103]: Plugin vfr_hud initialized
[ INFO] [1542203506.697688932]: Plugin vibration blacklisted
[ INFO] [1542203506.697867929]: Plugin vision_pose_estimate loaded
[ INFO] [1542203506.731083055]: Plugin vision_pose_estimate initialized
[ INFO] [1542203506.731397146]: Plugin vision_speed_estimate loaded
[ INFO] [1542203506.744171584]: Plugin vision_speed_estimate initialized
[ INFO] [1542203506.744435273]: Plugin waypoint loaded
[ INFO] [1542203506.765927861]: Plugin waypoint initialized
[ INFO] [1542203506.766180746]: Plugin wind_estimation loaded
[ INFO] [1542203506.767628664]: Plugin wind_estimation initialized
[ INFO] [1542203506.767695775]: Autostarting mavlink via USB on PX4
[ INFO] [1542203506.767924377]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1542203506.767974584]: Built-in MAVLink package version: 2018.10.10
[ INFO] [1542203506.768015961]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1542203506.768068895]: MAVROS started. MY ID 1.240, TARGET ID 1.1
SpawnModel script started
[INFO] [1542203507.317114, 0.000000]: Loading model XML from file
[INFO] [1542203507.317524, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[INFO] [1542203508.230323, 0.000000]: Calling service /gazebo/spawn_sdf_model
[ INFO] [1542203511.150599516, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1542203511.186807299, 0.002000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1542203511.195487749, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ERROR] [1542203511.196492402, 0.002000000]: Tried to advertise a service that is already advertised in this node [/camera/set_camera_info]
[ INFO] [1542203511.202761004, 0.002000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ERROR] [1542203511.202937406, 0.002000000]: Tried to advertise a service that is already advertised in this node [/camera/set_parameters]
[INFO] [1542203511.216599, 0.002000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1542203511.268092427, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ERROR] [1542203511.315160514, 0.002000000]: Tried to advertise a service that is already advertised in this node [/camera/set_camera_info]
[ INFO] [1542203511.332080992, 0.002000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ERROR] [1542203511.333970532, 0.002000000]: Tried to advertise a service that is already advertised in this node [/camera/set_parameters]
[ INFO] [1542203511.602053978, 0.036000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1542203511.602569828, 0.036000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1542203511.875940132, 0.082000000]: Physics dynamic reconfigure ready.
[vehicle_spawn_gleb_VirtualBox_11350_5973867746794150957-4] process has finished cleanly
log file: /home/gleb/.ros/log/61f06c14-e814-11e8-8ede-080027bc695c/vehicle_spawn_gleb_VirtualBox_11350_5973867746794150957-4*.log
[ INFO] [1542203511.959168905, 0.120000000]: Physics dynamic reconfigure ready.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
pxh> INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2018-11-14/13_51_52.ulg
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1542203512.823848303, 0.600000000]: udp0: Remote address: 127.0.0.1:14557
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
[ INFO] [1542203513.092884767, 0.722000000]: IMU: High resolution IMU detected!
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
INFO  [Unknown] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1542203514.423794044, 1.438000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1542203514.430152136, 1.444000000]: IMU: High resolution IMU detected!
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
[ INFO] [1542203514.614491879, 1.522000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1542203514.712142762, 1.556000000]: Drone to camera transform initialized
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
gzserver: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreRenderSystem.cpp:546: virtual void Ogre::RenderSystem::setDepthBufferFor(Ogre::RenderTarget*): Assertion `bAttached && "A new DepthBuffer for a RenderTarget was created, but after creation" "it says it's incompatible with that RT"' failed.
Aborted (core dumped)
[gazebo-2] process has died [pid 11376, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/gleb/catkin_ws/px4/Tools/sitl_gazebo/worlds/empty.world __name:=gazebo __log:=/home/gleb/.ros/log/61f06c14-e814-11e8-8ede-080027bc695c/gazebo-2.log].
log file: /home/gleb/.ros/log/61f06c14-e814-11e8-8ede-080027bc695c/gazebo-2*.log
gzclient: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreRenderSystem.cpp:546: virtual void Ogre::RenderSystem::setDepthBufferFor(Ogre::RenderTarget*): Assertion `bAttached && "A new DepthBuffer for a RenderTarget was created, but after creation" "it says it's incompatible with that RT"' failed.
Aborted (core dumped)
[gazebo_gui-3] process has died [pid 11381, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/gleb/.ros/log/61f06c14-e814-11e8-8ede-080027bc695c/gazebo_gui-3.log].
log file: /home/gleb/.ros/log/61f06c14-e814-11e8-8ede-080027bc695c/gazebo_gui-3*.log

**Comment by szebedy** [comment] 2018-11-15 15:24
Are you sure you executed all installation instructions?

**Comment by szebedy** [comment] 2018-11-15 15:26
Are you running the code on Ubuntu 16.04?
Are you sure you executed all installation instructions?

**Comment by logindiamant** [comment] 2018-11-15 19:36
I build 2 novel/original virtual machines on PC and notebook with Windows 10, Oracle VM VirtualBox, Ubuntu 16.04...
Step by step I follow you installation instruction without any errors

Gazebo run, I see scene with drone fiew seconds, then scene become gray color, Gazebo is crashed

**Comment by szebedy** [comment] 2018-11-15 21:10
Looks like the problem is with mavlink.

Do you start all nodes with the launch file? Can you try starting them separately and see when the problem occurs?

See Usage -> Simulation -> Run roscore, px4 with mavros, whycon, image_view and offboard_control

**Comment by szebedy** [comment] 2018-11-22 15:55
@logindiamant Did you find a solution to your problem? Can you tell us what caused it? It might help others with the same issue

**Comment by logindiamant** [comment] 2018-11-27 11:25
Thank you for care! I realy want to understand problem
Soon I will try solve it, step by step...
If possible, I try to save my virtual machine on googledisk

**Comment by szebedy** [comment] 2019-01-08 17:50
Hi @logindiamant, any update on this issue? Otherwise I'm going to close it

**Closed as completed** 2019-01-15 06:48 UTC
